In [142]:
from datetime import datetime
from dateutil.relativedelta import relativedelta, MO
import pandas as pd
patient_data = pd.read_csv("PATIENTS.csv")
diagnosis_data = pd.read_csv("D_ICD_DIAGNOSES.csv")
icd_data = pd.read_csv("DIAGNOSES_ICD.csv")

In [143]:
patient_data
patient_data['dob']=pd.to_datetime(patient_data['dob'], errors='coerce')
patient_data['dod']=pd.to_datetime(patient_data['dod'], errors='coerce')

patient_data.fillna(0)

,row_id,subject_id,gender,dob,dod,dod_hosp,dod_ssn,expire_flag
0,9467,10006,F,2094-03-05,2165-08-12,2165-08-12 00:00:00,2165-08-12 00:00:00,1
1,9472,10011,F,2090-06-05,2126-08-28,2126-08-28 00:00:00,0,1
2,9474,10013,F,2038-09-03,2125-10-07,2125-10-07 00:00:00,2125-10-07 00:00:00,1
3,9478,10017,F,2075-09-21,2152-09-12,0,2152-09-12 00:00:00,1
4,9479,10019,M,2114-06-20,2163-05-15,2163-05-15 00:00:00,2163-05-15 00:00:00,1
...,...,...,...,...,...,...,...,...
95,31838,44083,M,2057-11-15,2114-02-20,2114-02-20 00:00:00,2114-02-20 00:00:00,1
96,31853,44154,M,1878-05-14,2178-05-15,2178-05-15 00:00:00,2178-05-15 00:00:00,1
97,31867,44212,F,2078-06-16,2124-01-29,0,2124-01-29 00:00:00,1
98,31870,44222,M,2107-06-27,2182-08-03,2182-08-03 00:00:00,0,1
99,31872,44228,F,2112-10-22,2171-04-14,2171-04-14 00:00:00,0,1

In [144]:
icd_data
icd_data.fillna(0)

      row_id  subject_id  hadm_id  seq_num icd9_code
0     112344       10006   142345        1     99591
1     112345       10006   142345        2     99662
2     112346       10006   142345        3      5672
3     112347       10006   142345        4     40391
4     112348       10006   142345        5     42731
...      ...         ...      ...      ...       ...
1756  397673       44228   103379        7      1975
1757  397674       44228   103379        8     45182
1758  397675       44228   103379        9     99592
1759  397676       44228   103379       10      2449
1760  397677       44228   103379       11      2859

[1761 rows x 5 columns]

In [145]:
diagnosis_data
diagnosis_data.fillna(0)

,row_id,icd9_code,short_title,long_title
0,1,01716,Erythem nod tb-oth test,Erythema nodosum with hypersensitivity reactio...
1,2,01720,TB periph lymph-unspec,"Tuberculosis of peripheral lymph nodes, unspec..."
2,3,01721,TB periph lymph-no exam,"Tuberculosis of peripheral lymph nodes, bacter..."
3,4,01722,TB periph lymph-exam unk,"Tuberculosis of peripheral lymph nodes, bacter..."
4,5,01723,TB periph lymph-micro dx,"Tuberculosis of peripheral lymph nodes, tuberc..."
...,...,...,...,...
14562,14563,V8712,Contact/exposure benzene,Contact with and (suspected) exposure to benzene
14563,14564,V8719,Cont/exp haz aromat NEC,Contact with and (suspected) exposure to other...
14564,14565,V872,Cont/exp hazard chem NEC,Contact with and (suspected) exposure to other...
14565,14566,V8731,Contact/exposure mold,Contact with and (suspected) exposure to mold
14566,14567,V8732,Contact/exp algae bloom,Contact with and (suspected) exposure to algae...

In [151]:
 def diagnosis_pt(diagnosis_name):
    code = diagnosis_data[diagnosis_data['long_title']==diagnosis_name]['icd9_code'].item()
    test = icd_data[icd_data['icd9_code']==code]['subject_id']
    if test.empty:
      return "There are no patients with this diagnosis"
    else:
      return list(test)

In [147]:
diagnosis_pt('Contact with and (suspected) exposure to mold')

'There are no patients with this diagnosis'

In [148]:
diagnosis_pt('Intestinal infection due to Clostridium difficile')

[10043, 10045, 10094, 10102, 40595, 41976, 44228]

In [ ]:
pd.to_datetime(patient_data["dob"])
pd.to_datetime(patient_data["dod"])

0    2165-08-12
1    2126-08-28
2    2125-10-07
3    2152-09-12
4    2163-05-15
        ...
95   2114-02-20
96   2178-05-15
97   2124-01-29
98   2182-08-03
99   2171-04-14
Name: dod, Length: 100, dtype: datetime64[ns]

In [ ]:
patient_data['dob'] = pd.to_datetime(patient_data['dob'])
patient_data['dod'] = pd.to_datetime(patient_data['dod'])

In [ ]:
def dod_dob(diagnosis_name):
    code = diagnosis_data[diagnosis_data['long_title']==diagnosis_name]['icd9_code'].item()
    test = icd_data[icd_data['icd9_code']==code]['subject_id']
    test2 = test.values
    dob = patient_data[patient_data['subject_id'].isin(test2)]['dob']
    dod = patient_data[patient_data['subject_id'].isin(test2)]['dod']
    valid_indices = dob.notna() & dod.notna()
    dob=dob[valid_indices]
    dod = dod[valid_indices]
    if dob.empty:
        return "DOB is empty and operation cannot be preformed"
    if dod.empty:
        return "DOD is empty and operation cannot be preformed"
    differences = [(d.to_pydatetime() - b.to_pydatetime()).days for d, b in zip(dod, dob )]
    return differences

In [ ]:
dod_dob('Intestinal infection due to Clostridium difficile')

[29891, 25087, 109593, 25626, 27999, 24235, 21358]