In [2]:
import pandas as pd
import numpy as np
import pickle

In [3]:
# import wanted 2020 data and columns
data_2020 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2020',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2020.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2020,Alabama,Autauga County,South,55639.0,54929.0,2.0,2.25,5.29,17.88,...,5.36,18.95,12.07,14.68,29.36,0.02,1.0,0.02,1.0,0.02
1,2020,Alabama,Baldwin County,South,218289.0,216518.0,3.0,6.01,6.44,13.43,...,7.52,13.43,25.37,25.06,36.79,0.00,3.0,0.01,4.0,0.02
2,2020,Alabama,Barbour County,South,25026.0,24792.0,6.0,5.58,8.56,22.72,...,8.56,22.72,41.37,41.32,46.80,0.00,1.0,0.04,1.0,0.04
3,2020,Alabama,Bibb County,South,22374.0,22073.0,1.0,8.44,8.34,15.53,...,21.31,27.58,26.40,27.00,35.98,0.00,0.0,0.00,1.0,0.04
4,2020,Alabama,Blount County,South,57755.0,57164.0,1.0,10.56,9.68,17.69,...,9.82,19.89,26.16,27.23,34.04,0.00,2.0,0.03,1.0,0.02

In [4]:
# drop columns that are not the 50 states
print(data_2020["STATE"].unique())

allowed_states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
 'Connecticut', 'Delaware', 'Florida', 'Georgia',
 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
 'Mississippi', 'Missouri','Montana', 'Nebraska', 'Nevada', 'New Hampshire',
 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
 'Ohio', 'Oklahoma','Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']  

data_2020 = data_2020[data_2020["STATE"].isin(allowed_states)]
print(data_2020["STATE"].unique())

print(len(data_2020["STATE"].unique()))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'American Samoa'
 'Guam' 'Northern Mariana Islands' 'Puerto Rico' 'US Virgin Islands']
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50

In [5]:
# Count how many missing values exist before filling
missing_count = data_2020.isna().sum().sum()

# get location of each missing value
missing_locations = data_2020.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2020.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2020.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 72, column 'AHRF_USDA_RUCC_2013'
Missing value at row 73, column 'AHRF_USDA_RUCC_2013'
Missing value at row 94, column 'ACS_TOT_POP_WT'
Missing value at row 94, column 'ACS_TOT_POP_US_ABOVE1'
Missing value at row 94, column 'POS_MEDIAN_DIST_ED'
Missing value at row 94, column 'POS_MEAN_DIST_ED'
Missing value at row 94, column 'POS_MAX_DIST_ED'
Missing value at row 94, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 94, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 94, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 94, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 94, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 94, column 'POS_MAX_DIST_TRAUMA'
Filled 19 missing values with 'NA'.

In [6]:
# find what had missing data 
print(data_2020.iloc[68]["STATE"])
print(data_2020.iloc[68]["COUNTY"])
print(data_2020.iloc[94]["STATE"])
print(data_2020.iloc[94]["COUNTY"])

Alaska
Aleutians West Census Area
Alaska
Valdez-Cordova Census Area

In [7]:
# repeat for 2019 data 
data_2019 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2019',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2019.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2019,Alabama,Autauga County,South,55380.0,54699.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2019,Alabama,Baldwin County,South,212830.0,210908.0,3.0,6.21,6.51,18.61,...,7.50,18.61,26.28,25.65,36.06,0.00,3.0,0.01,4.0,0.02
2,2019,Alabama,Barbour County,South,25361.0,25050.0,6.0,5.89,8.58,22.69,...,8.58,22.69,41.52,41.27,46.80,0.00,1.0,0.04,1.0,0.04
3,2019,Alabama,Bibb County,South,22493.0,22141.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2019,Alabama,Blount County,South,57681.0,57191.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,2.0,0.03,1.0,0.02

In [8]:
# drop columns that are not the 50 states
data_2019 = data_2019[data_2019["STATE"].isin(allowed_states)]
print(data_2019["STATE"].unique())

print(len(data_2019["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2019.isna().sum().sum()

# get location of each missing value
missing_locations = data_2019.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2019.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2019.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print(data_2019.iloc[68]["STATE"])
print(data_2019.iloc[68]["COUNTY"])

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Filled 6 missing values with 'NA'.
Alaska
Aleutians West Census Area

In [9]:
# repeat for 2018 data 
data_2018 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2018',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2018.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2018.0,Alabama,Autauga County,South,55200.0,54509.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2018.0,Alabama,Baldwin County,South,208107.0,206023.0,3.0,6.21,6.51,18.61,...,7.50,18.61,26.28,25.65,36.06,0.00,3.0,0.01,4.0,0.02
2,2018.0,Alabama,Barbour County,South,25782.0,25469.0,6.0,5.89,8.58,22.69,...,8.58,22.69,41.52,41.27,46.80,0.00,1.0,0.04,1.0,0.04
3,2018.0,Alabama,Bibb County,South,22527.0,22112.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2018.0,Alabama,Blount County,South,57645.0,57144.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,2.0,0.03,1.0,0.02

In [10]:
# drop columns that are not the 50 states
data_2018 = data_2018[data_2018["STATE"].isin(allowed_states)]
print(data_2018["STATE"].unique())

print(len(data_2018["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2018.isna().sum().sum()

# get location of each missing value
missing_locations = data_2018.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2018.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2018.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print(data_2018.iloc[68]["STATE"])
print(data_2018.iloc[68]["COUNTY"])
print(data_2018.iloc[1815]["STATE"])
print(data_2018.iloc[1815]["COUNTY"])

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 1815, column 'ACS_TOT_POP_US_ABOVE1'
Filled 7 missing values with 'NA'.
Alaska
Aleutians West Census Area
New Mexico
Rio Arriba County

In [11]:
# repeat for 2017 data 

data_2017 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2017',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2017.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2017.0,Alabama,Autauga County,South,55036.0,54293.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2017.0,Alabama,Baldwin County,South,203360.0,201089.0,3.0,7.62,7.49,18.61,...,7.50,18.61,26.28,25.65,36.06,0.00,3.0,0.01,3.0,0.01
2,2017.0,Alabama,Barbour County,South,26201.0,25925.0,6.0,5.89,8.58,22.69,...,8.58,22.69,41.52,41.27,46.80,0.00,1.0,0.04,1.0,0.04
3,2017.0,Alabama,Bibb County,South,22580.0,22224.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2017.0,Alabama,Blount County,South,57667.0,57088.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,2.0,0.03,1.0,0.02

In [12]:
# drop columns that are not the 50 states
data_2017 = data_2017[data_2017["STATE"].isin(allowed_states)]
print(data_2017["STATE"].unique())

print(len(data_2017["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2017.isna().sum().sum()

# get location of each missing value
missing_locations = data_2017.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2017.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2017.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print(data_2017.iloc[68]["STATE"])
print(data_2017.iloc[68]["COUNTY"])
print(data_2017.iloc[85]["STATE"])
print(data_2017.iloc[85]["COUNTY"])

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 85, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 85, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 85, column 'POS_MAX_DIST_TRAUMA'
Filled 9 missing values with 'NA'.
Alaska
Aleutians West Census Area
Alaska
North Slope Borough

In [13]:
# repeat for 2016 data 

data_2016 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2016',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2016.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2016.0,Alabama,Autauga County,South,55049.0,54311.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2016.0,Alabama,Baldwin County,South,199510.0,197124.0,3.0,7.62,7.49,18.61,...,7.50,18.61,26.28,25.65,36.06,0.01,3.0,0.02,3.0,0.02
2,2016.0,Alabama,Barbour County,South,26614.0,26332.0,6.0,5.89,8.58,22.69,...,8.58,22.69,43.95,45.47,53.56,0.00,1.0,0.04,1.0,0.04
3,2016.0,Alabama,Bibb County,South,22572.0,22349.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2016.0,Alabama,Blount County,South,57704.0,57199.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,2.0,0.03,1.0,0.02

In [14]:
# drop columns that are not the 50 states
data_2016 = data_2016[data_2016["STATE"].isin(allowed_states)]
print(data_2016["STATE"].unique())

print(len(data_2016["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2016.isna().sum().sum()

# get location of each missing value
missing_locations = data_2016.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2016.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2016.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print((data_2016.iloc[68]["STATE"]), (data_2016.iloc[68]["COUNTY"]))
print((data_2016.iloc[85]["STATE"]), (data_2016.iloc[85]["COUNTY"]))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 85, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 85, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 85, column 'POS_MAX_DIST_TRAUMA'
Filled 9 missing values with 'NA'.
Alaska Aleutians West Census Area
Alaska North Slope Borough

In [15]:
# repeat for 2015 data 

data_2015 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2015',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2015.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2015,Alabama,Autauga County,South,55221.0,54662.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2015,Alabama,Baldwin County,South,195121.0,192790.0,3.0,7.62,7.49,18.61,...,7.50,18.61,26.28,25.65,36.06,0.01,3.0,0.02,3.0,0.02
2,2015,Alabama,Barbour County,South,26932.0,26692.0,6.0,5.89,8.58,22.69,...,8.58,22.69,43.95,45.47,53.56,0.00,1.0,0.04,1.0,0.04
3,2015,Alabama,Bibb County,South,22604.0,22359.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2015,Alabama,Blount County,South,57710.0,57157.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,2.0,0.03,1.0,0.02

In [16]:
# drop columns that are not the 50 states
data_2015 = data_2015[data_2015["STATE"].isin(allowed_states)]
print(data_2015["STATE"].unique())

print(len(data_2015["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2015.isna().sum().sum()

# get location of each missing value
missing_locations = data_2015.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2015.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2015.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print((data_2015.iloc[67]["STATE"]), (data_2015.iloc[67]["COUNTY"]))
print((data_2015.iloc[68]["STATE"]), (data_2016.iloc[68]["COUNTY"]))
print((data_2015.iloc[84]["STATE"]), (data_2016.iloc[84]["COUNTY"]))
print((data_2015.iloc[85]["STATE"]), (data_2016.iloc[85]["COUNTY"]))
print((data_2015.iloc[86]["STATE"]), (data_2016.iloc[86]["COUNTY"]))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 67, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 84, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 84, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 84, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 85, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 85, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 85, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 86, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 86, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 86, column 'POS_MAX_DIST_TRAUMA'
Filled 18 missing values with 'NA'.
Alaska Aleutians East Borough
Alaska Aleutians West Census Area
Alaska Nome Census Area
Alaska North Slope Borough
Alaska Northwest Arctic Borough

In [17]:
# repeat for 2014 data 

data_2014 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2014',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2014.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2014.0,Alabama,Autauga County,South,55136.0,54712.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2014.0,Alabama,Baldwin County,South,191205.0,188664.0,3.0,7.62,7.49,18.61,...,7.50,18.61,26.28,25.65,36.06,0.01,3.0,0.02,3.0,0.02
2,2014.0,Alabama,Barbour County,South,27119.0,26834.0,6.0,5.89,8.58,22.69,...,8.58,22.69,43.95,45.47,53.56,0.00,1.0,0.04,1.0,0.04
3,2014.0,Alabama,Bibb County,South,22653.0,22446.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2014.0,Alabama,Blount County,South,57645.0,57022.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,1.0,0.02,1.0,0.02

In [18]:
# drop columns that are not the 50 states
data_2014 = data_2014[data_2014["STATE"].isin(allowed_states)]
print(data_2014["STATE"].unique())

print(len(data_2014["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2014.isna().sum().sum()

# get location of each missing value
missing_locations = data_2014.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2014.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2014.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print((data_2014.iloc[67]["STATE"]), (data_2014.iloc[67]["COUNTY"]))
print((data_2014.iloc[68]["STATE"]), (data_2014.iloc[68]["COUNTY"]))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 67, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Filled 9 missing values with 'NA'.
Alaska Aleutians East Borough
Alaska Aleutians West Census Area

In [19]:
# repeat for 2013 data 

data_2013 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2013',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2013.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2013,Alabama,Autauga County,South,54907.0,54567.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2013,Alabama,Baldwin County,South,187114.0,184905.0,3.0,7.62,7.49,18.61,...,7.50,18.61,26.28,25.65,36.06,0.01,3.0,0.02,3.0,0.02
2,2013,Alabama,Barbour County,South,27321.0,27021.0,6.0,5.89,8.58,22.69,...,8.58,22.69,43.95,45.47,53.56,0.00,1.0,0.04,1.0,0.04
3,2013,Alabama,Bibb County,South,22754.0,22557.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2013,Alabama,Blount County,South,57623.0,56983.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,1.0,0.02,1.0,0.02

In [20]:
# drop columns that are not the 50 states
data_2013 = data_2013[data_2013["STATE"].isin(allowed_states)]
print(data_2013["STATE"].unique())

print(len(data_2013["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2013.isna().sum().sum()

# get location of each missing value
missing_locations = data_2013.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2013.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2013.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print((data_2013.iloc[67]["STATE"]), (data_2013.iloc[67]["COUNTY"]))
print((data_2013.iloc[68]["STATE"]), (data_2013.iloc[68]["COUNTY"]))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 67, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Filled 9 missing values with 'NA'.
Alaska Aleutians East Borough
Alaska Aleutians West Census Area

In [21]:
# repeat for 2012 data 

data_2012 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2012',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2012.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2012,Alabama,Autauga County,South,54590.0,54197.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2012,Alabama,Baldwin County,South,183226.0,180928.0,3.0,7.62,7.49,18.61,...,7.50,18.61,26.28,25.65,36.06,0.01,3.0,0.02,3.0,0.02
2,2012,Alabama,Barbour County,South,27469.0,27113.0,6.0,5.89,8.58,22.69,...,8.58,22.69,43.95,45.47,53.56,0.00,1.0,0.04,1.0,0.04
3,2012,Alabama,Bibb County,South,22769.0,22570.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2012,Alabama,Blount County,South,57466.0,56897.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,1.0,0.02,1.0,0.02

In [22]:
# drop columns that are not the 50 states
data_2012 = data_2012[data_2012["STATE"].isin(allowed_states)]
print(data_2012["STATE"].unique())

print(len(data_2012["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2012.isna().sum().sum()

# get location of each missing value
missing_locations = data_2012.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2012.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2012.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print((data_2012.iloc[67]["STATE"]), (data_2012.iloc[67]["COUNTY"]))
print((data_2012.iloc[68]["STATE"]), (data_2012.iloc[68]["COUNTY"]))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 67, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 69, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 69, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 69, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 74, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 74, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 74, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 78, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 78, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 78, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 80, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 80, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 80, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 81, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 81, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 81, column 'POS_MAX_DIST_TRAUMA'
Filled 24 missing values with 'NA'.
Alaska Aleutians East Borough
Alaska Aleutians West Census Area

In [23]:
# repeat for 2011 data 

data_2011 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2011',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2011.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2011,Alabama,Autauga County,South,53944.0,53436.0,2.0,2.20,5.33,18.07,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,1.0,0.02
1,2011,Alabama,Baldwin County,South,179523.0,177221.0,3.0,7.62,7.49,18.61,...,7.50,18.61,20.95,20.69,35.46,0.01,3.0,0.02,3.0,0.02
2,2011,Alabama,Barbour County,South,27546.0,27117.0,6.0,5.89,8.58,22.69,...,8.58,22.69,43.95,47.74,63.22,0.00,1.0,0.04,1.0,0.04
3,2011,Alabama,Bibb County,South,22746.0,22600.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2011,Alabama,Blount County,South,57140.0,56552.0,1.0,10.46,10.22,17.79,...,10.46,19.91,26.69,27.71,35.86,0.00,1.0,0.02,1.0,0.02

In [24]:
# drop columns that are not the 50 states
data_2011 = data_2011[data_2011["STATE"].isin(allowed_states)]
print(data_2011["STATE"].unique())

print(len(data_2011["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2011.isna().sum().sum()

# get location of each missing value
missing_locations = data_2011.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2011.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2011.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print((data_2011.iloc[67]["STATE"]), (data_2011.iloc[67]["COUNTY"]))
print((data_2011.iloc[68]["STATE"]), (data_2011.iloc[68]["COUNTY"]))
print((data_2011.iloc[69]["STATE"]), (data_2011.iloc[69]["COUNTY"]))
print((data_2011.iloc[74]["STATE"]), (data_2011.iloc[74]["COUNTY"]))
print((data_2011.iloc[78]["STATE"]), (data_2011.iloc[78]["COUNTY"]))
print((data_2011.iloc[80]["STATE"]), (data_2011.iloc[80]["COUNTY"]))
print((data_2011.iloc[81]["STATE"]), (data_2011.iloc[81]["COUNTY"]))
print((data_2011.iloc[90]["STATE"]), (data_2011.iloc[90]["COUNTY"]))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 67, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 69, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 69, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 69, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 74, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 74, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 74, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 78, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 78, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 78, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 80, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 80, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 80, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 81, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 81, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 81, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 90, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 90, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 90, column 'POS_MAX_DIST_TRAUMA'
Filled 27 missing values with 'NA'.
Alaska Aleutians East Borough
Alaska Aleutians West Census Area
Alaska Anchorage Municipality
Alaska Fairbanks North Star Borough
Alaska Kenai Peninsula Borough
Alaska Kodiak Island Borough
Alaska Lake and Peninsula Borough
Alaska Southeast Fairbanks Census Area

In [25]:
# repeat for 2010 data 

data_2010 = pd.read_excel("raw_data.xlsx", 
                          sheet_name= '2010',
                          usecols= ['STATE', 'YEAR', 'REGION', 'COUNTY', 'ACS_TOT_POP_WT','AHRF_USDA_RUCC_2013', 'ACS_TOT_POP_US_ABOVE1','POS_MEDIAN_DIST_ED', 'POS_MEAN_DIST_ED','POS_MAX_DIST_ED', 'POS_MEDIAN_DIST_MEDSURG_ICU', 'POS_MEAN_DIST_MEDSURG_ICU', 'POS_MAX_DIST_MEDSURG_ICU', 'POS_MEDIAN_DIST_TRAUMA', 'POS_MEAN_DIST_TRAUMA', 'POS_MAX_DIST_TRAUMA', 'POS_ASC_RATE', 'POS_TOT_HOSP_MEDSURG_ICU', 'POS_HOSP_MEDSURG_ICU_RATE', 'POS_TOT_HOSP_ED','POS_HOSP_ED_RATE'])
data_2010.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2010,Alabama,Autauga County,South,53155.0,52568.0,2.0,13.19,14.38,25.09,...,5.40,18.99,12.29,14.95,29.38,0.02,1.0,0.02,0.0,0.00
1,2010,Alabama,Baldwin County,South,175791.0,173522.0,3.0,10.68,10.90,23.31,...,7.50,18.61,20.95,20.69,35.46,0.01,3.0,0.02,2.0,0.01
2,2010,Alabama,Barbour County,South,27699.0,27230.0,6.0,23.10,22.73,25.34,...,8.58,22.69,43.95,47.74,63.22,0.00,1.0,0.04,0.0,0.00
3,2010,Alabama,Bibb County,South,22610.0,22449.0,1.0,9.24,8.97,15.08,...,21.39,26.37,25.09,26.33,33.91,0.00,0.0,0.00,1.0,0.04
4,2010,Alabama,Blount County,South,56692.0,56071.0,1.0,19.97,20.94,25.61,...,10.46,19.91,26.69,27.71,35.86,0.00,1.0,0.02,0.0,0.00

In [26]:
# drop columns that are not the 50 states
data_2010 = data_2010[data_2010["STATE"].isin(allowed_states)]
print(data_2010["STATE"].unique())

print(len(data_2010["STATE"].unique()))

# Count how many missing values exist before filling
missing_count = data_2010.isna().sum().sum()

# get location of each missing value
missing_locations = data_2010.isna()
rows, cols = np.where(missing_locations)
for r, c in zip(rows, cols):
    print(f"Missing value at row {r}, column '{data_2010.columns[c]}'")

# Fill all missing values with "NA"
data1 = data_2010.fillna("NA")

print(f"Filled {missing_count} missing values with 'NA'.")

print((data_2010.iloc[67]["STATE"]), (data_2010.iloc[67]["COUNTY"]))
print((data_2010.iloc[68]["STATE"]), (data_2010.iloc[68]["COUNTY"]))
print((data_2010.iloc[69]["STATE"]), (data_2010.iloc[69]["COUNTY"]))
print((data_2010.iloc[74]["STATE"]), (data_2010.iloc[74]["COUNTY"]))
print((data_2010.iloc[78]["STATE"]), (data_2010.iloc[78]["COUNTY"]))
print((data_2010.iloc[80]["STATE"]), (data_2010.iloc[80]["COUNTY"]))
print((data_2010.iloc[81]["STATE"]), (data_2010.iloc[81]["COUNTY"]))
print((data_2010.iloc[90]["STATE"]), (data_2010.iloc[90]["COUNTY"]))

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia' 'Hawaii' 'Idaho' 'Illinois'
 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Louisiana' 'Maine' 'Maryland'
 'Massachusetts' 'Michigan' 'Minnesota' 'Mississippi' 'Missouri' 'Montana'
 'Nebraska' 'Nevada' 'New Hampshire' 'New Jersey' 'New Mexico' 'New York'
 'North Carolina' 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
50
Missing value at row 67, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 67, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEDIAN_DIST_ED'
Missing value at row 68, column 'POS_MEAN_DIST_ED'
Missing value at row 68, column 'POS_MAX_DIST_ED'
Missing value at row 68, column 'POS_MEDIAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEAN_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MAX_DIST_MEDSURG_ICU'
Missing value at row 68, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 68, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 69, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 69, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 69, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 74, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 74, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 74, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 78, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 78, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 78, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 80, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 80, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 80, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 81, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 81, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 81, column 'POS_MAX_DIST_TRAUMA'
Missing value at row 90, column 'POS_MEDIAN_DIST_TRAUMA'
Missing value at row 90, column 'POS_MEAN_DIST_TRAUMA'
Missing value at row 90, column 'POS_MAX_DIST_TRAUMA'
Filled 30 missing values with 'NA'.
Alaska Aleutians East Borough
Alaska Aleutians West Census Area
Alaska Anchorage Municipality
Alaska Fairbanks North Star Borough
Alaska Kenai Peninsula Borough
Alaska Kodiak Island Borough
Alaska Lake and Peninsula Borough
Alaska Southeast Fairbanks Census Area

In [27]:
# summary stats of total number, maxiumum, mean, medium distance to er, trauma, and icu; total number of ambulatory surgery centers

In [28]:
# mak eone big dataframe 

df_cleaned = pd.concat([data_2020, data_2019, data_2018, data_2017, data_2016, data_2015, data_2014, data_2013], ignore_index=True)

df_cleaned['YEAR'] = df_cleaned['YEAR'].astype('Int64')
df_cleaned['AHRF_USDA_RUCC_2013'] = df_cleaned['AHRF_USDA_RUCC_2013'].astype('Int64')

df_cleaned.head()

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
0,2020,Alabama,Autauga County,South,55639.0,54929.0,2,2.25,5.29,17.88,...,5.36,18.95,12.07,14.68,29.36,0.02,1.0,0.02,1.0,0.02
1,2020,Alabama,Baldwin County,South,218289.0,216518.0,3,6.01,6.44,13.43,...,7.52,13.43,25.37,25.06,36.79,0.00,3.0,0.01,4.0,0.02
2,2020,Alabama,Barbour County,South,25026.0,24792.0,6,5.58,8.56,22.72,...,8.56,22.72,41.37,41.32,46.80,0.00,1.0,0.04,1.0,0.04
3,2020,Alabama,Bibb County,South,22374.0,22073.0,1,8.44,8.34,15.53,...,21.31,27.58,26.40,27.00,35.98,0.00,0.0,0.00,1.0,0.04
4,2020,Alabama,Blount County,South,57755.0,57164.0,1,10.56,9.68,17.69,...,9.82,19.89,26.16,27.23,34.04,0.00,2.0,0.03,1.0,0.02

In [29]:
df_cleaned[df_cleaned['AHRF_USDA_RUCC_2013'].isna()]

,YEAR,STATE,COUNTY,REGION,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,AHRF_USDA_RUCC_2013,POS_MEDIAN_DIST_ED,POS_MEAN_DIST_ED,POS_MAX_DIST_ED,...,POS_MEAN_DIST_MEDSURG_ICU,POS_MAX_DIST_MEDSURG_ICU,POS_MEDIAN_DIST_TRAUMA,POS_MEAN_DIST_TRAUMA,POS_MAX_DIST_TRAUMA,POS_ASC_RATE,POS_TOT_HOSP_MEDSURG_ICU,POS_HOSP_MEDSURG_ICU_RATE,POS_TOT_HOSP_ED,POS_HOSP_ED_RATE
72,2020,Alaska,Chugach Census Area,West,6495.0,6453.0,<NA>,3.44,3.44,5.89,...,114.39,130.92,24.45,24.45,42.54,0.0,0.0,0.0,4.0,0.62
73,2020,Alaska,Copper River Census Area,West,2894.0,2835.0,<NA>,16.63,16.63,16.63,...,142.15,142.15,78.58,78.58,78.58,0.0,0.0,0.0,1.0,0.35

In [30]:
df_cleaned.loc[72,'AHRF_USDA_RUCC_2013'] =

SyntaxError: invalid syntax (1638064709.py, line 1)

In [ ]:
df_cleaned['AHRF_USDA_RUCC_2013'].describe()

count     25129.0
mean      5.00975
std      2.707532
min           1.0
25%           2.0
50%           6.0
75%           7.0
max           9.0
Name: AHRF_USDA_RUCC_2013, dtype: Float64

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)

In [ ]:
df_cleaned.describe()

              YEAR  ACS_TOT_POP_WT  ACS_TOT_POP_US_ABOVE1  AHRF_USDA_RUCC_2013  POS_MEDIAN_DIST_ED  POS_MEAN_DIST_ED  POS_MAX_DIST_ED  POS_MEDIAN_DIST_MEDSURG_ICU  POS_MEAN_DIST_MEDSURG_ICU  POS_MAX_DIST_MEDSURG_ICU  POS_MEDIAN_DIST_TRAUMA  POS_MEAN_DIST_TRAUMA  POS_MAX_DIST_TRAUMA  POS_ASC_RATE  POS_TOT_HOSP_MEDSURG_ICU  POS_HOSP_MEDSURG_ICU_RATE  POS_TOT_HOSP_ED  POS_HOSP_ED_RATE
count      25131.0    2.513000e+04           2.512900e+04              25129.0        25130.000000      25130.000000     25130.000000                 25122.000000               25122.000000              25122.000000            25114.000000          25114.000000         25114.000000  25131.000000              25131.000000               25131.000000     25131.000000      25131.000000
mean   2016.500139    1.014954e+05           1.003157e+05              5.00975            7.664434          8.155618        15.032981                    12.228878                  12.703859                 19.840563               23.162723             23.406801            31.103632      0.011494                  1.853647                   0.038264         2.612630          0.100354
std       2.291516    3.256622e+05           3.217401e+05             2.707532           13.707003         13.419092        14.775390                    18.532922                  18.229941                 18.855607               23.527538             23.257161            23.997856      0.023152                  5.069786                   0.073053         5.005965          0.171490
min         2013.0    6.600000e+01           6.500000e+01                  1.0            0.130000          0.130000         0.130000                     0.130000                   0.130000                  0.130000                0.130000              0.130000             0.130000      0.000000                  0.000000                   0.000000         0.000000          0.000000
25%         2014.5    1.097925e+04           1.086800e+04                  2.0            2.850000          4.000000         9.680000                     3.460000                   4.660000                 11.690000                7.090000              7.760000            17.930000      0.000000                  0.000000                   0.000000         1.000000          0.010000
50%         2017.0    2.573900e+04           2.545500e+04                  6.0            5.040000          5.670000        13.060000                     6.930000                   7.330000                 16.200000               19.460000             19.450000            26.870000      0.000000                  1.000000                   0.020000         2.000000          0.040000
75%         2019.0    6.742375e+04           6.680200e+04                  7.0            8.540000          8.510000        17.190000                    16.790000                  16.690000                 23.390000               31.900000             31.730000            39.167500      0.020000                  2.000000                   0.040000         3.000000          0.110000
max         2020.0    1.010572e+07           9.988370e+06                  9.0          468.840000        468.840000       468.840000                   487.030000                 487.030000                487.030000              460.230000            460.230000           460.230000      0.430000                177.000000                   1.120000       147.000000          2.770000

In [ ]:
df_cleaned.groupby('AHRF_USDA_RUCC_2013').describe()

                       YEAR                                                                  ACS_TOT_POP_WT                                                                                   ACS_TOT_POP_US_ABOVE1                                                                                  POS_MEDIAN_DIST_ED                                                           POS_MEAN_DIST_ED                                                            POS_MAX_DIST_ED                                                               POS_MEDIAN_DIST_MEDSURG_ICU                                                            POS_MEAN_DIST_MEDSURG_ICU                                                              POS_MAX_DIST_MEDSURG_ICU                                                              POS_MEDIAN_DIST_TRAUMA                                                               POS_MEAN_DIST_TRAUMA                                                               POS_MAX_DIST_TRAUMA                                                             POS_ASC_RATE                                                  POS_TOT_HOSP_MEDSURG_ICU                                                 POS_HOSP_MEDSURG_ICU_RATE                                                  POS_TOT_HOSP_ED                                                 POS_HOSP_ED_RATE
                      count         mean       std     min      25%     50%      75%     max          count           mean            std      min       25%       50%        75%         max                 count           mean            std      min       25%       50%        75%        max              count       mean        std   min     25%   50%     75%     max            count       mean        std   min     25%   50%      75%     max           count       mean        std   min      25%     50%      75%     max                       count       mean        std   min    25%    50%      75%     max                     count       mean        std   min     25%     50%      75%     max                    count       mean        std   min     25%     50%      75%     max                  count       mean        std   min      25%     50%      75%     max                count       mean        std   min      25%     50%      75%     max               count       mean        std   min      25%     50%    75%     max        count      mean       std  min   25%   50%   75%   max                    count      mean        std  min  25%  50%  75%    max                     count      mean       std  min   25%   50%   75%   max           count      mean        std  min  25%  50%  75%    max            count      mean       std  min   25%   50%   75%   max
AHRF_USDA_RUCC_2013
1                    3448.0       2016.5   2.29162  2013.0  2014.75  2016.5  2018.25  2020.0         3448.0  407628.599478  778196.052278   4782.0  43654.50  139930.5  494602.50  10105722.0                3448.0  402820.004350  768780.358072   4763.0  43148.50  138338.0  490101.25  9988370.0             3448.0   5.321099   4.033947  0.48  2.5100  4.07   6.560   25.15           3448.0   5.593962   3.793767  0.56  3.1400  4.70   6.6100   23.77          3448.0  12.944461   6.518656  0.70   9.3100  12.120  15.3400   71.65                      3448.0   6.129063   5.047032  0.53   2.64   4.33   7.5600   27.03                    3448.0   6.476494   4.902847  0.59   3.225   4.870   7.6700   26.69                   3448.0  14.041146   7.112502  1.80   9.740  12.930  16.5600   71.65                 3448.0  14.034643  10.050097  0.58   5.4075  12.110  20.2700   49.84               3448.0  14.333118   9.842023  0.58   6.2600  12.400  20.3925   48.79              3448.0  24.094791  11.573266  0.70  16.2300  22.990  30.14   90.46       3448.0  0.018016  0.022287  0.0  0.00  0.01  0.03  0.16                   3448.0  5.568445  12.396620  0.0  1.0  2.0  5.0  177.0                    3448.0  0.014513  0.014788  0.0  0.00  0.01  0.02  0.10          3448.0  6.135731  11.969724  0.0  1.0  2.0  6.0  147.0           3448.0  0.022628  0.030670  0.0  0.01  0.01  0.03  0.38
2                    3025.0  2016.498843  2.292171  2013.0   2014.0  2016.0   2018.0  2020.0         3025.0  179786.182810  198718.730336   1773.0  34835.00   93419.0  274184.00   1038476.0                3025.0  177669.448595  196271.279402   1768.0  34434.00   92460.0  271492.00  1028084.0             3025.0   5.887481   5.130577  1.00  2.6400  4.34   7.120   44.53           3025.0   6.552922   4.836329  1.00  3.7300  5.05   7.4500   44.53          3025.0  15.541174   7.300373  1.00  11.1300  14.170  17.6700   75.77                      3025.0   7.554826   6.824156  1.00   2.80   4.83   9.7900   51.52                    3025.0   8.223246   6.427064  1.00   4.090   5.540   9.9400   51.52                   3025.0  17.767491   8.586487  1.00  12.090  15.710  21.6600   75.77                 3025.0  13.740046  11.163520  1.46   4.7400  11.500  19.8000  153.77               3025.0  14.384261  10.839750  2.15   5.7600  12.420  19.5300  155.14              3025.0  25.605719  12.583522  4.93  17.7200  23.880  30.11  185.49       3025.0  0.016271  0.020913  0.0  0.00  0.01  0.03  0.13                   3025.0  2.677686   3.076018  0.0  0.0  2.0  4.0   18.0                    3025.0  0.016327  0.019581  0.0  0.00  0.01  0.02  0.26          3025.0  3.472397   3.601695  0.0  1.0  2.0  5.0   26.0           3025.0  0.032350  0.043378  0.0  0.01  0.02  0.04  0.35
3                    2848.0       2016.5   2.29169  2013.0  2014.75  2016.5  2018.25  2020.0         2848.0   81475.818469   62599.912159     66.0  20338.75   76270.5  126766.00    250649.0                2848.0   80538.279846   61871.734197     65.0  20090.50   75332.0  125440.75   247525.0             2848.0   5.926791   5.029185  0.81  2.5300  3.82   7.580   30.54           2848.0   6.727749   4.607049  0.81  3.8000  5.09   7.7700   30.54          2848.0  15.157570   7.062524  0.81  10.9400  13.890  17.6225   64.18                      2848.0   7.643894   7.244340  0.88   2.69   4.08  11.0400   51.92                    2848.0   8.511239   6.757874  0.96   4.010   5.555  11.5400   51.92                   2848.0  17.638761   8.536786  1.69  12.080  15.720  21.3400   71.03                 2848.0  19.823771  20.568247  0.81   4.1500  16.655  28.9300  378.96               2848.0  20.336180  20.090745  0.81   5.9100  16.770  28.7100  378.38              2848.0  29.673171  20.529287  0.81  17.4825  25.290  37.00  384.39       2848.0  0.023262  0.030365  0.0  0.00  0.01  0.04  0.18                   2848.0  1.681882   1.583612  0.0  0.0  1.0  2.0    9.0                    2848.0  0.022184  0.029327  0.0  0.00  0.02  0.03  0.26          2848.0  2.308989   1.930482  0.0  1.0  2.0  3.0   10.0           2848.0  0.042802  0.058020  0.0  0.01  0.03  0.05  0.50
4                    1712.0       2016.5  2.291957  2013.0  2014.75  2016.5  2018.25  2020.0         1712.0   63378.005841   24356.346627  12646.0  45401.50   58500.0   76058.75    188629.0                1711.0   62703.400351   24129.747275  12446.0  44854.00   58025.0   75387.00   187183.0             1712.0   4.555263   2.905774  1.07  2.5800  3.98   5.745   22.46           1712.0   5.724136   2.579151  1.48  4.1600  5.16   6.6000   18.57          1712.0  15.085532   7.996352  2.65  10.7300  13.730  16.5950   71.01                      1712.0   5.769153   5.616038  1.20   2.71   4.25   6.7525   41.15                    1712.0   6.946998   6.003934  1.48   4.480   5.550   7.1200   58.86                   1712.0  16.826215  11.099175  2.65  11.740  14.290  18.8000  104.31                 1712.0  23.070911  16.614999  1.35   7.8075  22.490  33.0600   90.79               1712.0  23.449848  15.991161  2.60   8.5100  21.550  32.8500   84.50              1712.0  33.532354  18.963043  5.13  20.2900  29.485  43.05  151.48       1712.0  0.019912  0.023532  0.0  0.00  0.02  0.03  0.14                   1712.0  1.819509   1.236317  0.0  1.0  1.0  2.0    6.0                    1712.0  0.029807  0.019049  0.0  0.02  0.03  0.04  0.11          1712.0  2.323598   1.521082  0.0  1.0  2.0  3.0    9.0           1712.0  0.038470  0.024183  0.0  0.02  0.03  0.05  0.14
5                     736.0       2016.5  2.292846  2013.0  2014.75  2016.5  2018.25  2020.0          736.0   54560.141304   24651.222708  21902.0  36755.25   48915.5   65610.00    201350.0                 736.0   53895.569293   24376.532240  21493.0  36323.50   48061.5   64737.00   198803.0              736.0   3.849633   3.162185  0.96  2.1950  2.95   4.620   30.68            736.0   5.441603   3.104926  1.60  3.7200  4.49   6.0700   25.05           736.0  16.596440  11.856918  3.53  10.3100  13.465  18.5225   85.92                       736.0   4.030272   2.934776  0.96   2.35   3.03   5.0700   20.36                     736.0   5.806698   3.155369  1.60   3.890   5.020   6.2000   19.49                    736.0  18.066807  12.959011  3.53  10.745  14.945  19.4325   85.92                  736.0  22.713927  21.843819  1.34   4.0000  17.035  36.5425   98.06                736.0  23.168016  20.945815  2.04   5.5300  17.110  35.8775   96.39               736.0  33.367772  22.563060  3.84  15.7500  27.985  43.89  115.15        736.0  0.032840  0.030042  0.0  0.01  0.03  0.05  0.17                    736.0  1.789402   1.178237  0.0  1.0  1.0  2.0    7.0                     736.0  0.035068  0.020297  0.0  0.02  0.03  0.04  0.11           736.0  2.273098   1.660304  0.0  1.0  2.0  3.0    9.0            736.0  0.042677  0.024684  0.0  0.02  0.04  0.06  0.12
6                    4744.0       2016.5  2.291529  2013.0  2014.75  2016.5  2018.25  2020.0         4744.0   24744.118255   12667.801419   3441.0  14745.50   22687.5   32830.50     72346.0                4744.0   24476.655987   12536.396589   3422.0  14556.25   22430.5   32519.50    71356.0             4744.0   6.504924   4.657104  0.38  3.5500  5.61   8.190   43.96           4744.0   6.917003   4.176018  0.40  4.5475  5.98   8.0600   43.90          4744.0  13.453957   6.785610  0.40   9.5575  12.260  15.9400   71.18                      4744.0  11.679667   9.682353  0.40   4.87   8.32  16.5550   72.10                    4744.0  11.980694   9.270253  0.40   5.720   8.525  16.7300   66.98                   4744.0  18.527567  10.129701  0.40  11.920  16.670  22.5900   74.57                 4744.0  24.473919  15.142519  0.61  11.8500  23.370  34.8800   96.42               4744.0  24.484252  14.724823  0.90  10.8400  23.315  35.0600   95.55              4744.0  31.370961  15.537968  0.92  19.7200  29.490  41.98  105.22       4744.0  0.004511  0.015795  0.0  0.00  0.00  0.00  0.22                   4744.0  0.982083   0.917361  0.0  0.0  1.0  2.0    5.0                    4744.0  0.042738  0.047087  0.0  0.00  0.03  0.06  0.32          4744.0  1.948988   1.289087  0.0  1.0  2.0  2.0   10.0           4744.0  0.100369  0.085925  0.0  0.04  0.08  0.14  0.87
7                    3464.0       2016.5  2.291619  2013.0  2014.75  2016.5  2018.25  2020.0         3464.0   18900.325635   11104.318141   3393.0  10102.75   16438.5   25257.00     71230.0                3464.0   18690.411374   10988.124323   3357.0   9971.00   16268.0   24997.25    70668.0             3464.0   6.280742   7.753447  0.25  2.5475  4.78   7.430  121.20           3464.0   7.033233   7.025095  0.28  4.0200  5.63   7.8800  105.91          3464.0  14.332621  12.959700  0.28   8.2700  12.090  16.8500  194.87                      3464.0  14.170439  27.045763  0.38   3.53   7.15  17.9800  390.88                    3464.0  14.757688  26.806567  0.41   5.120   7.970  17.7400  390.88                   3464.0  21.941862  27.768260  0.41  10.920  16.390  25.3100  405.00                 3459.0  29.235886  34.326908  0.25   6.9800  22.920  38.7900  425.84               3459.0  29.438407  33.912525  0.28   8.2050  22.800  39.2500  425.84              3459.0  36.320113  35.052869  0.28  16.8850  28.960  46.83  428.63       3464.0  0.007670  0.021317  0.0  0.00  0.00  0.00  0.18                   3464.0  1.089492   0.943427  0.0  0.0  1.0  2.0    5.0                    3464.0  0.069402  0.080813  0.0  0.00  0.05  0.10  0.51          3464.0  1.945439   1.156119  0.0  1.0  2.0  2.0    8.0           3464.0  0.139711  0.111672  0.0  0.05  0.11  0.20  0.67
8                    1760.0       2016.5  2.291939  2013.0  2014.75  2016.5  2018.25  2020.0         1760.0    9676.212500    6315.764264    602.0   4781.75    8469.5   13311.50     36654.0                1760.0    9578.415909    6252.814686    577.0   4715.50    8393.5   13139.75    36298.0             1760.0  11.556125   8.756361  0.14  5.9200  9.83  15.320   77.18           1760.0  11.404295   8.640217  0.14  5.9900  9.33  14.4575   77.18          1760.0  14.620528   8.625894  0.14   9.3600  13.380  18.2600   77.18                      1760.0  19.895437  11.433168  0.62  12.50  18.62  24.6600   77.18                    1760.0  19.850619  11.404513  0.62  12.340  18.050  24.2675   77.18                   1760.0  23.157705  11.074978  0.62  15.760  21.255  28.6250   77.18                 1760.0  26.163665  18.887166  0.14  15.0700  24.830  34.6300  303.63               1760.0  26.135750  18.947667  0.14  14.7325  24.910  34.7500  303.63              1760.0  29.912057  19.299114  0.14  17.4400  28.310  39.17  303.63       1760.0  0.002778  0.029246  0.0  0.00  0.00  0.00  0.43                   1760.0  0.268182   0.594373  0.0  0.0  0.0  0.0    3.0                    1760.0  0.029330  0.072037  0.0  0.00  0.00  0.00  0.58          1760.0  1.118750   1.165201  0.0  0.0  1.0  2.0    5.0           1760.0  0.157500  0.219541  0.0  0.00  0.09  0.24  1.38
9                    3392.0       2016.5  2.291626  2013.0  2014.75  2016.5  2018.25  2020.0         3391.0    6082.203480    5060.509528     74.0   2380.50    4770.0    8278.50     29462.0                3391.0    6017.997346    5013.602476     74.0   2353.50    4707.0    8202.50    29138.0             3391.0  16.503775  32.933321  0.13  4.0600  9.14  19.480  468.84           3391.0  16.398030  32.715928  0.13  4.5850  8.98  19.0750  468.84          3391.0  19.373539  33.468265  0.13   6.5200  13.970  22.0000  468.84                      3383.0  26.262897  33.500564  0.13  11.61  20.67  30.3300  487.03                    3383.0  26.125454  33.241398  0.13  11.010  20.480  30.2400  487.03                   3383.0  29.264925  34.768887  0.13  15.690  23.140  32.7500  487.03                 3380.0  34.230269  35.266268  0.13  17.2800  27.190  43.3600  460.23               3380.0  34.232985  35.455275  0.13  16.8700  27.190  43.5100  460.23              3380.0  37.545491  37.546155  0.13  20.3800  30.360  45.64  460.23       3392.0  0.000041  0.001699  0.0  0.00  0.00  0.00  0.07                   3392.0  0.341097   0.678774  0.0  0.0  0.0  0.0    5.0                    3392.0  0.067037  0.149604  0.0  0.00  0.00  0.00  1.12          3392.0  1.123821   1.159118  0.0  0.0  1.0  2.0    6.0           3392.0  0.261990  0.344638  0.0  0.00  0.15  0.42  2.77

In [ ]:
for col in df_cleaned.columns:
    print(f"--- {col} ---")
    print(df_cleaned[col].describe())
    print()

--- YEAR ---
count        25131.0
mean     2016.500139
std         2.291516
min           2013.0
25%           2014.5
50%           2017.0
75%           2019.0
max           2020.0
Name: YEAR, dtype: Float64

--- STATE ---
count     25131
unique       50
top       Texas
freq       2032
Name: STATE, dtype: object

--- COUNTY ---
count                 25131
unique                 1878
top       Washington County
freq                    248
Name: COUNTY, dtype: object

--- REGION ---
count     25131
unique        4
top       South
freq      11369
Name: REGION, dtype: object

--- ACS_TOT_POP_WT ---
count    2.513000e+04
mean     1.014954e+05
std      3.256622e+05
min      6.600000e+01
25%      1.097925e+04
50%      2.573900e+04
75%      6.742375e+04
max      1.010572e+07
Name: ACS_TOT_POP_WT, dtype: float64

--- ACS_TOT_POP_US_ABOVE1 ---
count    2.512900e+04
mean     1.003157e+05
std      3.217401e+05
min      6.500000e+01
25%      1.086800e+04
50%      2.545500e+04
75%      6.680200e+04
max      9.988370e+06
Name: ACS_TOT_POP_US_ABOVE1, dtype: float64

--- AHRF_USDA_RUCC_2013 ---
count     25129.0
mean      5.00975
std      2.707532
min           1.0
25%           2.0
50%           6.0
75%           7.0
max           9.0
Name: AHRF_USDA_RUCC_2013, dtype: Float64

--- POS_MEDIAN_DIST_ED ---
count    25130.000000
mean         7.664434
std         13.707003
min          0.130000
25%          2.850000
50%          5.040000
75%          8.540000
max        468.840000
Name: POS_MEDIAN_DIST_ED, dtype: float64

--- POS_MEAN_DIST_ED ---
count    25130.000000
mean         8.155618
std         13.419092
min          0.130000
25%          4.000000
50%          5.670000
75%          8.510000
max        468.840000
Name: POS_MEAN_DIST_ED, dtype: float64

--- POS_MAX_DIST_ED ---
count    25130.000000
mean        15.032981
std         14.775390
min          0.130000
25%          9.680000
50%         13.060000
75%         17.190000
max        468.840000
Name: POS_MAX_DIST_ED, dtype: float64

--- POS_MEDIAN_DIST_MEDSURG_ICU ---
count    25122.000000
mean        12.228878
std         18.532922
min          0.130000
25%          3.460000
50%          6.930000
75%         16.790000
max        487.030000
Name: POS_MEDIAN_DIST_MEDSURG_ICU, dtype: float64

--- POS_MEAN_DIST_MEDSURG_ICU ---
count    25122.000000
mean        12.703859
std         18.229941
min          0.130000
25%          4.660000
50%          7.330000
75%         16.690000
max        487.030000
Name: POS_MEAN_DIST_MEDSURG_ICU, dtype: float64

--- POS_MAX_DIST_MEDSURG_ICU ---
count    25122.000000
mean        19.840563
std         18.855607
min          0.130000
25%         11.690000
50%         16.200000
75%         23.390000
max        487.030000
Name: POS_MAX_DIST_MEDSURG_ICU, dtype: float64

--- POS_MEDIAN_DIST_TRAUMA ---
count    25114.000000
mean        23.162723
std         23.527538
min          0.130000
25%          7.090000
50%         19.460000
75%         31.900000
max        460.230000
Name: POS_MEDIAN_DIST_TRAUMA, dtype: float64

--- POS_MEAN_DIST_TRAUMA ---
count    25114.000000
mean        23.406801
std         23.257161
min          0.130000
25%          7.760000
50%         19.450000
75%         31.730000
max        460.230000
Name: POS_MEAN_DIST_TRAUMA, dtype: float64

--- POS_MAX_DIST_TRAUMA ---
count    25114.000000
mean        31.103632
std         23.997856
min          0.130000
25%         17.930000
50%         26.870000
75%         39.167500
max        460.230000
Name: POS_MAX_DIST_TRAUMA, dtype: float64

--- POS_ASC_RATE ---
count    25131.000000
mean         0.011494
std          0.023152
min          0.000000
25%          0.000000
50%          0.000000
75%          0.020000
max          0.430000
Name: POS_ASC_RATE, dtype: float64

--- POS_TOT_HOSP_MEDSURG_ICU ---
count    25131.000000
mean         1.853647
std          5.069786
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max        177.000000
Name: POS_TOT_HOSP_MEDSURG_ICU, dtype: float64

--- POS_HOSP_MEDSURG_ICU_RATE ---
count    25131.000000
mean         0.038264
std          0.073053
min          0.000000
25%          0.000000
50%          0.020000
75%          0.040000
max          1.120000
Name: POS_HOSP_MEDSURG_ICU_RATE, dtype: float64

--- POS_TOT_HOSP_ED ---
count    25131.000000
mean         2.612630
std          5.005965
min          0.000000
25%          1.000000
50%          2.000000
75%          3.000000
max        147.000000
Name: POS_TOT_HOSP_ED, dtype: float64

--- POS_HOSP_ED_RATE ---
count    25131.000000
mean         0.100354
std          0.171490
min          0.000000
25%          0.010000
50%          0.040000
75%          0.110000
max          2.770000
Name: POS_HOSP_ED_RATE, dtype: float64

In [31]:
df_cleaned["REGION"].unique()

array(['South', 'West', 'Northeast', 'Midwest'], dtype=object)

In [35]:
south_states = df_cleaned[df_cleaned['REGION'] == 'South']['STATE'].unique()
print("South:", south_states)

west_states = df_cleaned[df_cleaned['REGION'] == 'West']['STATE'].unique()
print("West:", west_states)

northeast_states = df_cleaned[df_cleaned['REGION'] == 'Northeast']['STATE'].unique()
print("Northeast:", northeast_states)

midwest_states = df_cleaned[df_cleaned['REGION'] == 'Midwest']['STATE'].unique()
print("Midwest:", midwest_states)

South: ['Alabama' 'Arkansas' 'Delaware' 'Florida' 'Georgia' 'Kentucky'
 'Louisiana' 'Maryland' 'Mississippi' 'North Carolina' 'Oklahoma'
 'South Carolina' 'Tennessee' 'Texas' 'Virginia' 'West Virginia']
West: ['Alaska' 'Arizona' 'California' 'Colorado' 'Hawaii' 'Idaho' 'Montana'
 'Nevada' 'New Mexico' 'Oregon' 'Utah' 'Washington' 'Wyoming']
Northeast: ['Connecticut' 'Maine' 'Massachusetts' 'New Hampshire' 'New Jersey'
 'New York' 'Pennsylvania' 'Rhode Island' 'Vermont']
Midwest: ['Illinois' 'Indiana' 'Iowa' 'Kansas' 'Michigan' 'Minnesota' 'Missouri'
 'Nebraska' 'North Dakota' 'Ohio' 'South Dakota' 'Wisconsin']

In [ ]:
df_cleaned.to_parquet("clean_data.parquet")